gemma4:12b
hf.co/unsloth/DeepSeek-R1-0528-Qwen3-8B-GGUF:UD-Q8_K_XL
hf.co/Jackrong/Qwen3.5-9B-DeepSeek-V4-Flash-GGUF:Q8_0
hf.co/unsloth/DeepSeek-R1-Distill-Qwen-14B-GGUF:Q5_K_M
hf.co/unsloth/Qwen3.6-27B-GGUF:UD-IQ2_M
gemma4:e4b
